language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

matrix:
  include:
    - osx_image: xcode7.3
      env: RAKETASK="ios[iOS StaticLib,latest,build test,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode7.3
      env: RAKETASK="ios[iOS Framework,latest,build test,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode7.3
      env: RAKETASK="osx[Mac Framework,x86_64,build test,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode7.3
      env: RAKETASK="tvos[tvOS Framework,latest,build test,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode8
      env: RAKETASK="ios[iOS StaticLib,latest,build-for-testing test-without-building,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode8
      env: RAKETASK="ios[iOS Framework,latest,build-for-testing test-without-building]"
    - osx_image: xcode8
      env: RAKETASK="osx[Mac Framework,x86_64,build-for-testing test-without-building,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"
    - osx_image: xcode8
      env: RAKETASK="tvos[tvOS Framework,latest,build-for-testing test-without-building,-DOHHTTPSTUBS_SKIP_TIMING_TESTS=1]"

script:
  - rake "$RAKETASK"

before_deploy:
  - carthage build --no-skip-current
  - carthage archive OHHTTPStubs

deploy:
  provider: releases
  api_key:
    secure: LJfogUcxlaXczvPyu+s2SAG7SXyhjQbc/kCiNjEO61ehLg0dK0bmfXHm0yeBQQPoQCF5qiWC+5HYQnCaMNmEhP4WHy6RZtmmrg1iiNbeLsRzk8COm2vv+zRgoFXU5K7j2LkfvTSrLPTYR1d+PM/S/XJzMDxrJjryM+mf12DxlnA=
  file: OHHTTPStubs.framework.zip
  skip_cleanup: true
  on:
    tags: true
